@baseUrl = http://localhost:888/api

# @name is_unique_email
POST  {{baseUrl}}/users/is-unique-email HTTP/1.1
Content-Type: application/json

{
    "email": "user@gmail.com"
}

###

# @name is_unique_username
POST  {{baseUrl}}/users/is-unique-username HTTP/1.1
Content-Type: application/json

{
    "username": "user1"
}

###

# @name create_user
POST {{baseUrl}}/users HTTP/1.1
Content-Type: application/json

{
    "username": "user",
    "email": "user@gmail.com",
    "password": "secret",
    "phone": "901234567"
}

###

# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "username": "user1",
    "password": "secret"
}

###
@token = {{ login.response.body.token }}
@refresh_token = "{{ login.response.body.refresh_token }}"

# @name refresh-token
POST {{baseUrl}}/auth/refresh-token HTTP/1.1
Content-Type: application/json

{
    "refresh_token": {{refresh_token}}
}

###

# @name get_all_users
GET {{baseUrl}}/users?page=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_user_by_id
GET {{baseUrl}}/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###


# @name get_user_by_token
GET {{baseUrl}}/users/me HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name change_password
PUT {{baseUrl}}/users/change-password HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "old_password": "secret",
    "password": "secret-put",
    "confirm_password": "secret"
}

###

# @name update_user_by_id
PATCH {{baseUrl}}/users/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "email": "a_put@a.a",
    "phone": "+998901234567"
}

###

# @name delete_user_by_id
DELETE  {{baseUrl}}/users/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name create_multi_store
POST {{baseUrl}}/multi-stores HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "1-multi-store"
}

###

# @name get_all_multi_stores
GET {{baseUrl}}/multi-stores HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_multi_store_by_id
GET {{baseUrl}}/multi-stores/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name update_multi_store_by_id
PATCH {{baseUrl}}/multi-stores/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "20-multi-store",
    "profit": "{'default':'15'}",
    "barcodeTtn": 1523,
    "nds": 15
}

###

# @name delete_multi_store_by_id
DELETE {{baseUrl}}/multi-stores/9 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name create_store
POST {{baseUrl}}/stores HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "2-store",
    "multiStoreId": 1
}

###

# @name get_all_stores
GET {{baseUrl}}/stores?multiStoreId=1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name get_store_by_id
GET {{baseUrl}}/stores/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name update_store_by_id
PATCH {{baseUrl}}/stores/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "20-store-patch",
    "isActive": true
}

###

# @name delete_store_by_id
DELETE {{baseUrl}}/stores/2 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}